tabela = {['Oi'] = 'Hi'
,['Tchau'] = 'Bye'
,['Casa'] = 'House'
,['Caneta'] = 'Pen'
,['Lapis'] = 'Pencil'
,['Aviao'] = 'Plane'
,['Carro'] = 'Car'
,['Computador'] = 'Computer'
,['Passaro'] = 'Bird'
,['Navio'] = 'Ship'
}